let DATA=[], BUILD={version:'',updated:''};
let nums=[], currentLesson=0, currentVersion='', fs=+(localStorage.getItem('acimFS')||21), lh=+(localStorage.getItem('acimLH')||1.85), scan=100, saveTimer=null;
document.documentElement.style.setProperty('--fs',fs+'px'); document.documentElement.style.setProperty('--lh',lh);
const $=id=>document.getElementById(id); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byLesson=n=>DATA.filter(x=>x.lesson===n);
function renderRuns(runs){return (runs||[]).map(r=>{let text=esc(r.text);if(r.italic)text=`<em>${text}</em>`;if(r.emphasis)text=`<strong class="journey-emphasis">${text}</strong>`;return text}).join('')}
function renderJourneyBlocks(blocks){return blocks.map(b=>{if(b.type==='title')return '';if(b.type==='figure')return `<figure class="journey-figure"><a href="${esc(b.src)}" target="_blank" rel="noopener"><img src="${esc(b.src)}" alt="${esc(b.alt)}"></a><figcaption>${esc(b.alt)} · <a href="${esc(b.src)}" target="_blank" rel="noopener">查看大图</a></figcaption><details><summary>图中文字</summary>${renderJourneyBlocks(b.textBlocks||[])}</details></figure>`;const tag=b.type==='heading'?'h3':'p';return `<${tag}>${renderRuns(b.runs)}</${tag}>`}).join('')}
function renderJourney(pages){return `<details class="journey-toc"><summary>本资料目录（${pages.length}页）</summary><ol>${pages.map(p=>`<li><a href="#journey-page-${p.number}">${p.number}. ${esc(p.title)}</a></li>`).join('')}</ol></details>${pages.map(p=>`<section class="journey-page" id="journey-page-${p.number}"><div class="journey-page-number">第 ${p.number} 页</div><h2>${esc(p.title)}</h2>${renderJourneyBlocks(p.blocks)}</section>`).join('')}`}
function isHeading(t){return /^第 \d+ 页$/.test(t.trim()) || /^(注[释釋]|练习说明|練習說明|目的[:：]|早晚安静时光|早晚安靜時光|每小时整点忆念|每小時整點憶念|面对诱惑时的回应|面對誘惑時的回應|备注[:：]|備註[:：]|導言|导言)$/.test(t.trim()) || /^(目的|早晚安静时光|早晚安靜時光|每小时整点忆念|每小時整點憶念|面对诱惑时的回应|面對誘惑時的回應|备注|備註)[：:]/.test(t.trim())}
function isNote(t){return /^(\d{3}|[〔\[]?\d{3}[〕\]]?)/.test(t.trim()) && !/^1\d?\s/.test(t.trim())}
function renderText(blocks){return (blocks||[]).map(t=>{let s=String(t).trim(),cls=''; if(isHeading(s))cls='heading'; else if(isNote(s))cls='note'; else if(/^\d+\s/.test(s))cls='numbered'; return `<p class="${cls}">${esc(s)}</p>`}).join('')}
function currentKey(){return `scroll:${currentLesson}:${currentVersion}`}
function saveScroll(){clearTimeout(saveTimer); saveTimer=setTimeout(()=>localStorage.setItem(currentKey(),String(scrollY)),120)}
function restoreScroll(){const y=+(localStorage.getItem(currentKey())||0); setTimeout(()=>{const anchor=currentLesson==='journey'&&location.hash?document.getElementById(location.hash.slice(1)):null;if(anchor)anchor.scrollIntoView({behavior:'instant'});else scrollTo({top:y,behavior:'instant'})},40)}
function urlView(){return currentVersion==='罗伯佩里注解'?'perry':currentVersion==='复习五导言'?'intro':'text'}
function updateURL(){const u=new URL(location.href);u.searchParams.set('lesson',currentLesson);u.searchParams.set('view',urlView());history.replaceState(null,'',u)}
function renderNav(filter=''){const nav=$('nav');nav.innerHTML='';[...nums,...new Set(DATA.filter(x=>x.kind==='material').map(x=>x.lesson))].forEach(n=>{const arr=byLesson(n),label=arr.find(x=>x.version!=='罗伯佩里注解')?.title||arr[0].title;const hay=(n+' '+arr.map(x=>x.title+' '+x.version).join(' ')).toLowerCase();if(filter&&!hay.includes(filter.toLowerCase()))return;const b=document.createElement('button');b.className='navitem'+(n===currentLesson?' active':'');b.innerHTML=`<b>${arr[0].kind==='material'?'学习资料':`第 ${n} 课`}</b><small>${esc(label)}</small>`;b.onclick=()=>{currentLesson=n;currentVersion='';show(true);closeDrawer()};nav.appendChild(b)})}
function show(resetScroll=false){const arr=byLesson(currentLesson);if(!arr.length)return;let item=arr.find(x=>x.version===currentVersion)||arr[0];currentVersion=item.version;localStorage.setItem('acimLesson',currentLesson);localStorage.setItem('acimVersion',currentVersion);updateURL();$('kicker').textContent=`${item.kind==='material'?'学习资料':`第 ${currentLesson} 课`} · ${item.version}`;$('title').textContent=item.title;$('meta').textContent=`来源：${item.source||''} · 资料版本 ${BUILD.version||''}`;const vb=$('versionbar');vb.innerHTML='';arr.forEach(v=>{const b=document.createElement('button');b.textContent=v.version;b.className=v.version===currentVersion?'active':'';b.onclick=()=>{localStorage.setItem(currentKey(),String(scrollY));currentVersion=v.version;show(true)};vb.appendChild(b)});const c=$('content');c.classList.toggle('text-content',!(item.images&&item.images.length));if(item.images&&item.images.length){c.innerHTML=`<div class="scancontrols"><button id="scanMinus">缩小原页</button><button id="scanPlus">放大原页</button><span>原版扫描页</span></div><div class="scanwrap" id="scanwrap">${item.images.map(src=>`<img class="scanpage" alt="第${currentLesson}课原版页面" src="${src}">`).join('')}</div>`;setTimeout(()=>{const w=$('scanwrap');if(w)w.style.setProperty('--scan',scan+'%');$('scanPlus')?.addEventListener('click',()=>{scan=Math.min(240,scan+20);w.style.setProperty('--scan',scan+'%')});$('scanMinus')?.addEventListener('click',()=>{scan=Math.max(100,scan-20);w.style.setProperty('--scan',scan+'%')})},0)}else c.innerHTML=item.pages?renderJourney(item.pages):renderText(item.blocks);renderNav($('search').value);const i=nums.indexOf(currentLesson),prev=i>0?nums[i-1]:null,next=i>=0&&i<nums.length-1?nums[i+1]:null;for(const id of ['prev','prevTop']){$(id).disabled=!prev;$(id).onclick=()=>{if(prev){currentLesson=prev;currentVersion='';show(true)}}}for(const id of ['next','nextTop']){$(id).disabled=!next;$(id).onclick=()=>{if(next){currentLesson=next;currentVersion='';show(true)}}}if(resetScroll)scrollTo({top:0,behavior:'instant'});else restoreScroll()}
function closeDrawer(){$('sidebar').classList.remove('open')}
function setTheme(v){if(v==='light')v='white';if(!['paper','white','dark'].includes(v))v='paper';document.body.classList.remove('paper','white','dark');document.body.classList.add(v);localStorage.setItem('acimTheme',v);const b=$('themeBtn');if(b){b.textContent=v==='paper'?'纸色':v==='white'?'白色':'夜间';b.title='阅读底色：'+b.textContent+'（点击切换）'}}
async function checkUpdate(manual=false){try{if('serviceWorker'in navigator){const r=await navigator.serviceWorker.getRegistration();await r?.update()}const v=await fetch('version.json?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());if(v.version!==BUILD.version){if(confirm(`发现新内容版本 ${v.version}，现在刷新吗？`))location.reload()}else if(manual)alert('当前已经是最新版本：'+BUILD.version)}catch(e){if(manual)alert('暂时无法联网检查更新；离线内容仍可继续阅读。')}}
function touchDistance(t){const dx=t[0].clientX-t[1].clientX,dy=t[0].clientY-t[1].clientY;return Math.hypot(dx,dy)}
function setupPinchResize(){
  const el=$('content');
  let active=false,startDist=0,startFS=fs,lastFS=fs,gestureStartFS=fs;
  const apply=v=>{lastFS=Math.max(14,Math.min(40,+v.toFixed(1)));fs=lastFS;document.documentElement.style.setProperty('--fs',fs+'px')};
  const commit=()=>{if(!active)return;active=false;fs=lastFS;localStorage.setItem('acimFS',fs)};
  el.addEventListener('touchstart',e=>{if(!el.classList.contains('text-content')||e.touches.length!==2)return;e.preventDefault();active=true;startDist=touchDistance(e.touches);startFS=fs;lastFS=fs},{passive:false});
  el.addEventListener('touchmove',e=>{if(!active||e.touches.length!==2||!startDist)return;e.preventDefault();apply(startFS*(touchDistance(e.touches)/startDist))},{passive:false});
  el.addEventListener('touchend',e=>{if(e.touches.length<2)commit()},{passive:true});
  el.addEventListener('touchcancel',commit,{passive:true});
  el.addEventListener('gesturestart',e=>{if(!el.classList.contains('text-content'))return;e.preventDefault();active=true;gestureStartFS=fs;lastFS=fs},{passive:false});
  el.addEventListener('gesturechange',e=>{if(!active)return;e.preventDefault();apply(gestureStartFS*(e.scale||1))},{passive:false});
  el.addEventListener('gestureend',e=>{e.preventDefault();commit()},{passive:false});
}
function setupInstall(){let deferred=null;const btn=$('installBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;btn.hidden=false});btn.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;btn.hidden=true}else{$('installHelp').classList.add('show')}};$('installClose').onclick=()=>$('installHelp').classList.remove('show')}
async function init(){try{BUILD=await fetch('version.json',{cache:'no-store'}).then(r=>r.json()).catch(()=>({version:'offline'}));const IDX=await fetch('lessons-index.json?v='+encodeURIComponent(BUILD.version)).then(r=>r.json()); const parts=await Promise.all((IDX.files||[]).map(f=>fetch(f+'?v='+encodeURIComponent(BUILD.version)).then(r=>r.json()))); DATA=parts.flat();nums=[...new Set(DATA.filter(x=>x.kind!=='material').map(x=>x.lesson))].sort((a,b)=>a-b);const q=new URLSearchParams(location.search);const key=q.get('lesson')||localStorage.getItem('acimLesson')||nums[0];currentLesson=DATA.some(x=>x.kind==='material'&&x.lesson===key)?key:+key;if(!byLesson(currentLesson).length)currentLesson=nums[0];const vq=q.get('view');currentVersion=vq==='perry'?'罗伯佩里注解':(vq==='intro'?'复习五导言':(vq==='text'?'课文':(localStorage.getItem('acimVersion')||'')));$('status').textContent=`资料更新：${BUILD.updated||''} · ${nums.length} 个课程 · ${DATA.filter(x=>x.version==='罗伯佩里注解').length} 篇罗伯·佩里注解${DATA.some(x=>x.kind==='material')?' · '+DATA.filter(x=>x.kind==='material').length+' 份学习资料':''}`;show(false);setupInstall();setupPinchResize();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').then(r=>r.update()).catch(()=>{});setTimeout(()=>checkUpdate(false),2500)}catch(e){$('content').innerHTML='<div class="loading">内容载入失败。若你直接双击本地文件，请改为部署到 HTTPS 网站后打开；PWA 需要通过网页服务器运行。</div>';console.error(e)}}
$('search').addEventListener('input',e=>renderNav(e.target.value));$('drawerBtn').onclick=()=>$('sidebar').classList.toggle('open');$('fontPlus').onclick=()=>{fs=Math.min(36,fs+1);document.documentElement.style.setProperty('--fs',fs+'px');localStorage.setItem('acimFS',fs)};$('fontMinus').onclick=()=>{fs=Math.max(14,fs-1);document.documentElement.style.setProperty('--fs',fs+'px');localStorage.setItem('acimFS',fs)};$('linePlus').onclick=()=>{lh=Math.min(2.5,+(lh+.08).toFixed(2));document.documentElement.style.setProperty('--lh',lh);localStorage.setItem('acimLH',lh)};$('lineMinus').onclick=()=>{lh=Math.max(1.3,+(lh-.08).toFixed(2));document.documentElement.style.setProperty('--lh',lh);localStorage.setItem('acimLH',lh)};$('themeBtn').onclick=()=>{const cur=document.body.classList.contains('paper')?'paper':document.body.classList.contains('white')?'white':'dark';setTheme(cur==='paper'?'white':cur==='white'?'dark':'paper')};$('updateBtn').onclick=()=>checkUpdate(true);setTheme(localStorage.getItem('acimTheme')||'paper');addEventListener('scroll',saveScroll,{passive:true});addEventListener('popstate',()=>{const q=new URLSearchParams(location.search);if(q.get('lesson')!==String(currentLesson)||q.get('view')!==urlView())location.reload()});init();
